### ISSUE TITLE
setDidClickLinkBlock in MLLinkLabel

### ISSUE THREAD

**Issue by jmartos89** [molon/MLLabel#11]
The method setDidClickLinkBlock in MLLinkLabel  is only called on a long press, this is normal?

**Comment by molon** [comment]
@jmartos89 No, it's strange. could you give me a example which triggers this.

**Comment by jmartos89** [comment]
[cell.contentLabel setDidClickLinkBlock:^(MLLink *link, NSString *linkText, MLLinkLabel *label) {
                [self clickUrl:linkText];
            }];

cell.contentLabel is a MLLinkLabel

**Comment by molon** [comment]
@jmartos89  maybe there is a gesture over the cell? if yes. https://github.com/molon/MLLabel/blob/master/Example/MLLabel/ViewControllers/ListNoNibTableViewCell.m#L73
