### ISSUE TITLE
emoji表情高度稍高

### ISSUE THREAD

**Issue by ZWZZZ** [molon/MLLabel#13]
有emoji表情的时候，好像mllabel的高度会比没有emoji表情的时候高？有可能搞成同一高度的吗？

**Comment by molon** [comment]
@ZWZZZ 这个应该不会吧，你是从这里直接搞得最新代码么？最一开始是有这种问题。后来我改了相关的应该已经ok了。里面有个ClipExpresstion的例子，如果测试还是觉有问题的话，可否提供下测试代码。:)

**Comment by ZWZZZ** [comment]
呃，不是自定义表情哦，就是系统输入法打出来的emoji在上面直接显示的时候

**Comment by molon** [comment]
@ZWZZZ 实在抱歉哈，哥们，在下觉得这个即使会出现也是应该的。毕竟iOS系统默认认为它就应该这么高。
