### ISSUE TITLE
添加约束不能适应大小

### ISSUE THREAD

**Issue by gaohomway** [molon/MLLabel#15]
我在swift中用NSLayoutConstraint添加约束，添加在UITableViewCell 上，但是不能适应大小，什么问题呢

**Comment by molon** [comment]
@weiFans 修正了些问题https://github.com/molon/MLLabel/commit/7149bb6542407b25291a146bf34ff3f459043c73
并且更新pod到1.8版本
请测试，如果不是这个问题的请再次说明下。 :)

**Comment by gaohomway** [comment]
@molon 好的，多谢多谢～
