### ISSUE TITLE
cell里面MLLable的重用机制。

### ISSUE THREAD

**Issue by xiaoyang00c** [molon/MLLabel#17]
如何清除掉已添加的链接属性。
- (MLLink_)addLinkWithType:(MLLinkType)type value:(NSString_)value range:(NSRange)range;
- (BOOL)addLink:(MLLink*)link;

**Comment by molon** [comment]
@xiaoyang00c `addLink`相关的方法都是在对Label设置了文本之后调用的。再次对这个Label设置文本会清除掉已添加的。
