### ISSUE TITLE
没有办法垂直对齐啊

### ISSUE THREAD

**Issue by zhouyang8304** [molon/MLLabel#19]

**Comment by molon** [comment]
@zhouyang8304 可否详细描述一下。不是太明白

**Comment by zhouyang8304** [comment]
VerticalAlignmen 好像 没有啊

**Comment by molon** [comment]
@zhouyang8304 默认垂直居中，和UILabel行为一致。没有垂直居上居下的实现，因为我想不到什么情况下会有这种需求。
