### ISSUE TITLE
有时会导致越界这个问题，放在cell上的

### ISSUE THREAD

**Issue by hzx157** [molon/MLLabel#28]
**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[NSBigMutableString _getBlockStart:end:contentsEnd:forRange:stopAtLineSeparators:]: Range {0, 20} out of bounds; string length 6'
**\* First throw call stack:
(0x183cb82d8 0x1954e40e4 0x183cb8218 0x184adab14 0x191a741fc 0x191a74990 0x191a7d930 0x191aa9e8c 0x191aaa1ac 0x191acf160 0x191acea28 0x184ada21c 0x191ad0c90 0x1007c8044 0x1007cd5c4 0x10014c6e4 0x1001d1a40 0x1001d2428 0x1001d22dc 0x1004044d8 0x1886f5760 0x18803de1c 0x188038884 0x188709f94 0x1887cf3d0 0x188837b10 0x188706b6c 0x188837294 0x1889f9a88 0x1889ed890 0x1887d9268 0x1886f5760 0x18803de1c 0x188038884 0x188038728 0x188037ebc 0x188037c3c 0x18808e1f4 0x184e69470 0x183c5adc4 0x183c6fa54 0x183c6f9b4 0x183c6d934 0x183b992d4 0x18d3af6fc 0x18875efac 0x100651eb0 0x195b62a08)
libc++abi.dylib: terminating with uncaught exception of type NSException
Printing description of attributedText:
然后在昵称上面的圆框点一下就能修改信息了（----------这里是打印内容）

**Comment by molon** [comment]
@hzx157 如果打印这个NSBigMutableString 的话是什么内容呢？
