### ISSUE TITLE
计算的高度有问题

### ISSUE THREAD

**Issue by ghost** [molon/MLLabel#3]
![3eb79cdf-52a0-4ddc-ac30-e3454ad37ffd](https://cloud.githubusercontent.com/assets/9336572/9266549/4564d1c2-4275-11e5-98aa-cbdd236f521a.png)

多了一行的高度

**Comment by molon** [comment]
@doyanaml 你好，请问下这个问题是存在还是不存在?

**Comment by ghost** [comment]
现在问题不存在了，是因为我的那个text里面有多余的换行符，所以计算的高度多了一行。建议默认去掉结尾的换行

**Comment by molon** [comment]
@doyanaml 没问题就好。默认去掉换行这个还是不添加了。没准有人有这种需求呢。哈哈。。
