### ISSUE TITLE
你好，我想问一下表情显示的大小可以设置吗？

### ISSUE THREAD

**Issue by hongdong** [molon/MLLabel#30]
你好，我想问一下表情显示的大小可以设置吗？想要设置小一点

**Comment by molon** [comment]
@hongdong 这个需求的话，需要你自己改库里代码了。
MLTextAttachment.m里

```
attachmentBoundsForTextContainer:xxxxx
```

这个方法里修改最终的width和height，抱歉，这种需求个人感觉不是很必要，所以不会在库里加上，因为默认表情是和字体行高一致的。
