### ISSUE TITLE
文本内容含有\n的情况，\n及之后的内容都丢失了

### ISSUE THREAD

**Issue by tiasn** [molon/MLLabel#31]
**服务器返回的文本内容含有\n的情况，\n及之后的内容都丢失了**😢

**Comment by molon** [comment]
@tiasn 你的numberoflines 是如何设置的。而这段文本具体是有几个\n

**Comment by tiasn** [comment]
numberoflines 是0
两个\n  
label高度 +10之后 好了 
可能是我的label高度计算不准确😓
