### ISSUE TITLE
设置dataDetectorTypes无效

### ISSUE THREAD

**Issue by codingZero** [molon/MLLabel#37]
我设置MLLinkLabel的dataDetectorTypes属性为MLDataDetectorTypeNone，它还是会把label中的数字变成链接，找了半天没找到原因，最终我只能把phoneNumber的正则改了😂

**Comment by molon** [comment]
@codingZero 
哥们，似乎没发现你说的问题啊。可否提供详细的你的使用方式信息。
我的测试代码  LinkViewController.m 67行:

```
if (result==1) {
        //测试绘制背景色不会受到行间距设置的影响
        self.label.lineHeightMultiple = 1.5f;
        self.label.lineSpacing = 10.0f;
        LABEL.dataDetectorTypes = MLDataDetectorTypeNone;
    }
```

**Comment by codingZero** [comment]
@molon  不好意思，是我自己失误了，我创建了两个label，只设置了其中一个😂，谢谢你的框架😁

**Comment by molon** [comment]
@codingZero 不客气。 :)
