### ISSUE TITLE
大神，关于MLLinklabel的使用我想请教个问题。现在ml可以检测出链接，但是我们想让检测出来的链接以“网页链接”四个字的形式展示出来，不是以原网址的形式展示要怎么做呢

### ISSUE THREAD

**Issue by qiaovc** [molon/MLLabel#40]
我在源代码里找了，没找到，求教😭

**Comment by molon** [comment]
@Verchen 抱歉，并不支持这个。
如果非要这样做的话，我简单说下实现方式你可以尝试去解决。
自己用正则(正则在`MLLinkLabel.m`头部找得到)去检测文本中链接字符串区间，可以参考`MLExpressionManager`里`expressionAttributedStringWithString:expression:`方法，把最终文本整理成带`网页链接`的样式的`NSAttributedString`。
但是要注意在每次append`网页链接`的这段`NSAttributedString`时，需要给予其属性key为`NSLinkAttributeName`，value为url字符串。
然后在使用`MLLinkLabel`的时候确保`dataDetectorTypes`里包含`MLDataDetectorTypeAttributedLink`
而且若想对其开启自动检测type机制的话，还需要对`dataDetectorTypesOfAttributedLinkValue`做些许设置，否则的话回调里会统一识别Link是`MLLinkTypeOther`。

:)
