### ISSUE TITLE
didClick代理方法不调用问题。但是didLongPress有调用

### ISSUE THREAD

**Issue by whihail** [molon/MLLabel#41]
不知为何MLLinkLabel一直不调用这两个方法：
- (void)touchesEnded:(NSSet *)touches withEvent:(UIEvent *)event
- (void)touchesMoved:(NSSet *)touches withEvent:(UIEvent *)event

调完
- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event
  之后就直接调
- (void)touchesCancelled:(NSSet *)touches withEvent:(UIEvent *)event

我也不知道什么原因，写法和你的demo一模一样，但是就是不知道为什么，我用的pod导入你的代码

**Comment by molon** [comment]
@chengjiaming `userInteractionEnabled` 是不是设置为NO了。

**Comment by whihail** [comment]
设置成YES了哦！
现在发现需要长按好久大概4、5秒才会回调didClick、都不知道什么问题、你的dome是没有问题的。

发自我的 iPhone

**Comment by molon** [comment]
@chengjiaming 
那你看下我demo里的
`ListNoNibTableViewCell.m`
`- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch`
这里的实现，你有木有处理，可能是由于被上层手势给阻挡了。需要对手势的回调进行下过滤处理。

**Comment by whihail** [comment]
有的呀！

发自我的 iPhone

**Comment by molon** [comment]
@chengjiaming 那就不滋道了。。  没有更详细的信息来判断啊。。
