### ISSUE TITLE
获取高度

### ISSUE THREAD

**Issue by matchboxy** [molon/MLLabel#43]
我添加了一个 NSTextAttachment ，然后使用 sizeThatFits 计算有误。  当这个 attachment 在最后折行的时候，总是少计算一行。   貌似它没有参与计算。  请问，使用 MLLinkLabel 该如何获取 attributeString 的高度呢？

**Comment by molon** [comment]
抱歉，这段时间有点忙，回复晚了。
高度的话都是通过`preferredSizeWithMaxWidth:`方法，不过内部其实也是使用的`sizeThatFits:`方法。

可否提供更详细的信息，有代码片段最好啊。其实`MLExpressionManager`里表示表情图片的部分也是使用的`NSTextAttachment`。

**Comment by molon** [comment]
@matchboxy
