### ISSUE TITLE
电话号码的正则匹配有缺陷

### ISSUE THREAD

**Issue by whihail** [molon/MLLabel#44]
类似
 +8613978432345 
8613743237899 
135-3458-9876
等电话号码不能匹配到，能否完善一下匹配电话的正则表达式

**Comment by molon** [comment]
@chengjiaming 如果只是你说的这三种倒是可以添加，但是例如非86的或者 +86135-3458-9876等等就太多太多了，就不好弄了。也容易识别到其他内容。

**Comment by molon** [comment]
@chengjiaming 
\d{3}-\d{8}|\d{3}-\d{7}|\d{4}-\d{8}|\d{4}-\d{7}|1+[3578]+\d{9}|[+]861+[3578]+\d{9}|861+[3578]+\d{9}|1+[3578]+\d{1}-\d{4}-\d{4}|\d{8}|\d{7}
http://tool.oschina.net/regex/   你试下看看能满足你条件么，如果能得话我就更新到库里。

**Comment by dev-jw** [comment]
有个bug，我输入我的邮箱时，匹配到的结果是前8位，即为电话类型。例: **57398655**8@qq.com

**Comment by molon** [comment]
@SmallLion 这个愁人啊，我把号码的正则优先级放到邮箱前面了。我一会得空想想咋调一调还能兼容。

**Comment by molon** [comment]
@SmallLion @chengjiaming  已修复。pod 1.9.2

**Comment by XavierLost** [comment]
40089097890 ??
