### ISSUE TITLE
MLLabel能对图片设置点击事件吗？

### ISSUE THREAD

**Issue by sujiewen** [molon/MLLabel#47]
你好，MLLabel能对图片设置点击事件吗？

**Comment by molon** [comment]
@sujiewen Sorry, 不可以。

**Comment by swsdyg** [comment]
@molon 您好，我正在研究text kit,然后就发现了您的这个库，我发现您的MLLabel是继承的UILabel,现在也有一些疑惑，就是如果MLLabel直接继承UITextView的话应该会比较简单，您是出于内存的考虑还是其它的原因，希望作者能不吝赐教，谢谢!

**Comment by chenjsa** [comment]
UITextView可编辑不太适合吧

**Comment by molon** [comment]
@swsdyg 当时倒没有考虑那么多，这个库完全是因为有类似微信的IM需求做出来的副产品。实际上可以完全不继承于UILabel，只不过一般开发时候使用UILabel的地方很多，用起来比较习惯，就直接处理成与其保持一致的属性啊使用方式啊什么的。

**Comment by swsdyg** [comment]
@molon 谢谢您的回复
