### ISSUE TITLE
下面代码，直接crash了，怎么修复？

### ISSUE THREAD

**Issue by GitterYang** [molon/MLLabel#48]
- (MLLinkLabel *)contentLabel {
  if (!_contentLabel) {
      _contentLabel = [[MLLinkLabel alloc] init];
      _contentLabel.textAlignment = NSTextAlignmentCenter;
      _contentLabel.font = [UIFont systemFontOfSize:kContentFontSize];
      _contentLabel.numberOfLines = 0;
      _contentLabel.textColor = [UIColor blackColor];
      NSString *html = @"您好";
     _contentLabel.attributedText = [NSAttributedString attributedStringWithHTML:html]; //crash了
  }
  return _contentLabel;
  }

**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'

这个该怎么解决呢？

**Comment by molon** [comment]
![image](https://cloud.githubusercontent.com/assets/3739161/16937027/133c7742-4d9e-11e6-8bbb-0676f43fc0d7.png)
@CoderEic 哥们，我没有重现你的问题。可否麻烦fork下MLLabel，然后在里面某个地方重现下这个问题？

**Comment by GitterYang** [comment]
我把有问题的部分从我代码中抽出来，那样写又没问题，放在我项目中就crash了，我还是自己检查检查吧，多谢了!

**Comment by molon** [comment]
@CoderEic 好吧，若是库有问题请及时和我说。 :)

**Comment by GitterYang** [comment]
好的，Thank you.
