### ISSUE TITLE
html字体

### ISSUE THREAD

**Issue by Ackerman64** [molon/MLLabel#5]
你好！请问能自行设置html字体显示的字体大小吗？我用您的demo试了下貌似不可以。不知道是不是我的用法不对？

**Comment by molon** [comment]
html解析出来的`NSAttributedString`是默认设置了`NSFontAttributeName`属性的。
既然`NSAttributedString`的某区间字体属性被设置，肯定不能以Label设置的字体为准了，所以造成了你说的情况。

而在解析之后去对`NSAttributedString`矫正字体的话肯定是不OK的。因为没准某个区间的字体必须是特殊的，之后去矫正势必会覆盖。

所以解决办法只有一个，直接改html。例如外面包一层

```
<div style='font-size:14px'>
....
</div>
```
