### ISSUE TITLE
html和普通文本共存时\n和\r失效

### ISSUE THREAD

**Issue by huapeng222** [molon/MLLabel#54]
`html=@"如您需临时调高信用额度，请直接回复“调额”。\r\n如您有现金需求，<a href=\"https://www.baidu.com\" >点击这里</a>，立即借款！\r\n如您需大额消费分期额度，<a href=\"https://www.baidu.com\" >点击这里</a>，立即申请！<br>测试</br>";`
![simulator screen shot 2016 8 25 11 58 16](https://cloud.githubusercontent.com/assets/7056869/17956282/3d1b6b74-6abb-11e6-91d6-4c4fea294495.png)
![img_4322](https://cloud.githubusercontent.com/assets/7056869/17956297/571a0602-6abb-11e6-884f-f51de15fe3f2.PNG)

**Comment by molon** [comment]
@huapeng222 html转attributedString这个实际我还真没怎么用过。不过我觉得都用html了，直接用 br 就已经满足需求了啊，用\r\n本身就怪怪的。
刚才又看了下代码，转html的方法是sdk里自带的，默认行为，感觉没什么必要把默认行为修改掉了。

**Comment by huapeng222** [comment]
已经直接把里边的\n替换成br来解决了。另外。谢谢了。

发自我的 iPhone
