### ISSUE TITLE
numberOfLines 和 lineSpacing同时设置出错

### ISSUE THREAD

**Issue by iOSXH** [molon/MLLabel#56]
当numberOfLines 和 lineSpacing都大于0时，只会显示numberOfLines-1行，请问怎么解决？

**Comment by molon** [comment]
@iOSXH 我刚才试了下 没重现你说的问题，可否fork下库，然后在demo里重现一下？

**Comment by molon** [comment]
@iOSXH 
感谢反馈，之前没有给予更多信息所以没去搞。现在有人遇到同样的问题，已经解决，可以先尝试下最新的。
https://github.com/molon/MLLabel/commit/9a226bbe666aab4d1a821160a145da2702383b58
顺便稍微改了其他的一些东西，等几天再release。
