### ISSUE TITLE
间距不对

### ISSUE THREAD

**Issue by mydy1987** [molon/MLLabel#6]
Molon:
        谢谢你的库，之前我用的是MLEmojiLabel，后来看到这里有最新的MLLabel，扩展性更强，可实现更多的功能，于是换成了新的MLLabel。换了之后一切正常，只有一个问题，我项目里的间距感觉要比Demo里的间距要大很多。如果是纯文字，间距会小一点，如果文字里带有表情，间距就会大一些。
     Demo里的效果：

<img width="290" alt="2015-09-06 2 52 24" src="https://cloud.githubusercontent.com/assets/6948457/9703018/bce50f20-54a7-11e5-9bc4-c069a01b7d7b.png">
     项目里做出来的效果：
<img width="309" alt="2015-09-06 2 53 48" src="https://cloud.githubusercontent.com/assets/6948457/9703021/d27ee31a-54a7-11e5-8cb2-09e4fafb5f6b.png">
     文字的行间距变高了，请问如何破，我的代码与你都没有看到有不一样的地方。都是用Xib。请指教啊！

**Comment by molon** [comment]
@mydy1987  关于文字无表情行和有表情行的间距问题的解释 https://github.com/molon/MLLabel/issues/1
，你这个是蛮奇怪的。你用的表情是库里ClippedExpression.bundle吗？

另外MLLabel的行间距默认是0，如果想设置的话，可以设置lineHeightMultiple，例如设置为1.1，则行间距为行高的0.1倍。

**Comment by mydy1987** [comment]
@molon 行间距变高是我设置了

**Comment by mydy1987** [comment]
@molon 找到了原因，行间距变高是我设置了：
    self.lineHeightMultiple = 1.3f;
无表情行和有表情行的间距的问题在更新的最新的库后也得到了解决。THX!
