### ISSUE TITLE
MLLabel 设置lineSpacing 和 numberOfLines， 显示有问题

### ISSUE THREAD

**Issue by leizGit** [molon/MLLabel#60]
在使用 MLLabel 的时候，设置最大显示行数numberOfLines，然后设置lineSpacing时，显示的真实行数要少于numberOfLines值，例如numberOfLines＝6， lineSpacing＝5，数据很长时，显示有问题

**Comment by molon** [comment]
@leizGit 感谢反馈，已解决，可以尝试下。
https://github.com/molon/MLLabel/commit/9a226bbe666aab4d1a821160a145da2702383b58
顺便稍微改了其他的一些东西，等几天再release。
