### ISSUE TITLE
在Swift中使用MLLinkLabel问题

### ISSUE THREAD

**Issue by yansun2006** [molon/MLLabel#62]
在Swift中使用MLLinkLabel的时候，设置linkTextAttributes的换行模式，会不显示链接的文本
let textLabel = MLLinkLabel()
textLabel.linkTextAttributes = [NSUnderlineStyleAttributeName: NSUnderlineStyle.styleSingle]

但是直接使用Int类型就可以，如下：
textLabel.linkTextAttributes = [NSUnderlineStyleAttributeName:1]

**Comment by molon** [comment]
抱歉，不怎么懂swift~

**Comment by linbo8303** [comment]
textLabel.linkTextAttributes = [NSUnderlineStyleAttributeName: NSUnderlineStyle.styleSingle.rawValue]

**Comment by yansun2006** [comment]
感谢 @linbo8303
