### ISSUE TITLE
之前匹配表情用到俩个bundle 文件包，现在用一个就可以了吗？

### ISSUE THREAD

**Issue by jerroy** [molon/MLLabel#64]
之前匹配表情用到俩个bundle 文件包，现在用一个就可以了吗？

**Comment by molon** [comment]
一直是一个啊，demo里有俩只是为了演示优化掉表情空白边缘。
一个是优化前的，一个是优化后的。
正式用的时候按demo里把自己的表情图片优化掉空白边缘整理打包成一份bundle使用即可。
