### ISSUE TITLE
MLLinkLabel中设置文字颜色，遇到数字颜色显示错误

### ISSUE THREAD

**Issue by qingkongsun** [molon/MLLabel#65]
这是一个Demo，msg中8888数字颜色显示有问题，作者能帮忙看下吗？谢啦!!☆⌒(*＾-゜)v
    MLLinkLabel *label = [[MLLinkLabel alloc] initWithFrame:CGRectMake(0, 100, 400, 20)];
    [self.view addSubview:label];
    
    NSString *msg = @"大家好哈哈哈哈哈哈哈8888888888888";
    NSMutableAttributedString *attr = [[NSMutableAttributedString alloc] initWithString:msg attributes:@{NSForegroundColorAttributeName:[UIColor orangeColor]}];
    label.attributedText = attr;

**Comment by molon** [comment]
MLLinkLabel默认是会去识别电话号码的，你这个太像电话号码了，所以变成链接颜色了。
```
@interface MLLinkLabel : MLLabel

//默认为MLDataDetectorTypeURL|MLDataDetectorTypePhoneNumber|MLDataDetectorTypeEmail|MLDataDetectorTypeAttributedLink，自动检测除了@和#话题的全部类型并且转换为链接
@property (nonatomic, assign) MLDataDetectorTypes dataDetectorTypes;
```
