### ISSUE TITLE
设置链接点击时的阴影背景为圆角

### ISSUE THREAD

**Issue by jacylouis** [molon/MLLabel#68]
你好,如果要把链接点击时的阴影背景(即 ActiveLinkBackground )设置成像系统Label的dataDetectorTypes 那样点击时的圆角样式应该从哪里修改,找了很久,没有找到突破点.

**Comment by molon** [comment]
@jacylouis 绘制背景色那块是在这个文件最下面，但是你要绘制圆角的还得做一些额外处理才可以。
https://github.com/molon/MLLabel/blob/master/Classes/Helper/MLLabelLayoutManager.m

**Comment by jacylouis** [comment]
谢谢大神及时回复,但是我对CGContext 的计算不太熟,不知可否提供点帮助,或者留个联系方式方便交流一下

**Comment by molon** [comment]
@jacylouis 这和计算关系不是太大，下面的你整整看，有什么问题再说。
```
 for (NSInteger i=0; i<rectCount; i++) {
                //找到相交的区域并且绘制
                CGRect validRect = CGRectIntersection(lineBounds, rectArray[i]);
                if (!CGRectIsEmpty(validRect)) {
//这个validRect你稍微往外扩一点，或者不扩，然后下面就是绘制这个矩形区域的方法，你Google下咋绘制圆角矩形替换掉就是了。
                    CGContextFillRect(ctx, validRect);
                }
            }
```

**Comment by jacylouis** [comment]
好的,非常感谢你!!
