### ISSUE TITLE
copy文本的功能

### ISSUE THREAD

**Issue by lypcliuli** [molon/MLLabel#69]
您好 我使用了MLLabel做的论坛类型的列表页面，用户发表的文章使用的MLLabel展示的，但是发现MLLabel没有复制的功能，还麻烦告知是不是还未预留copy文字的功能，谢谢

**Comment by molon** [comment]
@lypcliuli 呃，MLLabel一开始是为了给微信聊天信息那种玩意而造的，继承自UILabel。预留了copy方法，但是没有像TextView那样的默认拷贝操作，拷贝操作需要自己去用menu控件来实现，调用MLLabel的copy方法。

https://github.com/molon/MLLabel/blob/master/Classes/MLLabel.m#L703-L717
