### ISSUE TITLE
有个关于表情的问题请教一下你

### ISSUE THREAD

**Issue by jerroy** [molon/MLLabel#70]
安卓那边的应该是第三方的表情，他通过融云传过来，可以显示表情，但是其他页面上的label 显示的是表情字符，但是我复制的那个表情字符放到融云消息了，它又不能显示了，放到之前显示的地方它还是不能显示，遇到的现象就是只要是我自己打印出来的表情字符，他就不能匹配 ，有遇到这种情况吗？谢谢

**Comment by molon** [comment]
虽然不知道具体情况，但是感觉应该是因为转义而发生你说的情况。 转义来转义去，多次转义了什么的。你得仔细瞅瞅你复制出来的玩意和以前的那个哪里不一致，实在不行挨个char比对。

然后表情字符转换成表情的原理其实很简单，就是字符串通过正则匹配出哪块代表表情字符，然后将其剔除替换成表情图像放到`NSAttributedString`里。
所以你该有那个正则吧，网上搜个正则测试器，辅助测试你的串问题出在哪啊。

其他的也就帮不上你了~

**Comment by jerroy** [comment]
他发送过来的直接显示表情，然后我从后台拿到的那个表情的字符串，然后复制粘贴 输入 就不能转成表情了~~头大~

**Comment by molon** [comment]
@jerroy 如果他发送过来的你直接丢到UILabel上都直接显示表情的话，那说明他发送过来的不是自定义表情，而是emoji表情，就是unicode编码，后台给的不能用只能说明中间被安卓那边做了些处理了吧。 具体不清楚。 你肯定还是需要将俩字符串拿出来细致比对不同来定位问题啊。

**Comment by jerroy** [comment]
恩恩  谢谢你哈 有点思路了
