### ISSUE TITLE
数字会自动另起一行

### ISSUE THREAD

**Issue by zlp10** [molon/MLLabel#71]
在字符串里面, 如果有一串臭长的纯数字, 那么 这串数字会另起一行显示...大神帮忙看下!

**Comment by molon** [comment]
你是不想另起一行？ 那你lineBreakMode搞成NSLineBreakByCharWrapping试试。
如果不行，去继承下然后参考下MLLinkLabel.m里的一段代码处理下即可。
https://github.com/molon/MLLabel/blob/master/Classes/MLLinkLabel.m#L519-L536
