### ISSUE TITLE
话题俩井号，第二个井号不识别

### ISSUE THREAD

**Issue by lypcliuli** [molon/MLLabel#74]
您好，我们的帖子里面有话题特殊颜色展示在文本里面，这个MLlabel只能判断到第一个井号和文本，后一个井号不含，比如我的帖子内容是“#今天是个好日子#对今天不错”，  加特殊话题颜色之后只有“##今天是个好日子”这一部分变色，后面一个井号没有覆盖到

**Comment by molon** [comment]
@lypcliuli 支持的话题是`#xxxxxx `这样的，一个#号的，建议改成这种，没必要用俩#去区分，和`@xxx `一样，需要强制和后面分隔开的话，中间加个空格即可。

当然了，可能你们本身的数据已经是俩#号了，那就直接改源码来用吧，不太好直接放库里支持，觉得这个属于比较特殊的需求。
MLLinkLabel.m里的，改成这个试试。
```
REGULAREXPRESSION(HashtagRegularExpression, @"#([\\u4e00-\\u9fa5\\w\\-]+)#")
```

**Comment by lypcliuli** [comment]
您好，非常感谢 已修改源码实现我们的需求

发自我的 iPhone
