### ISSUE TITLE
有没有办法将AttributedString转回普通String

### ISSUE THREAD

**Issue by wangweihu** [molon/MLLabel#78]
eg:已转化成AttributedString的字符串：我是小😊😎  转回到对应的普通字符串：我是小[开心][酷~]

**Comment by molon** [comment]
这个倒是没提供，一般不需要吧，本身这个普通字符串你本身就肯定知道啊，只不过在给到label的时候label需要处理成attrStr用来渲染罢了。

**Comment by wangweihu** [comment]
这个能提供一些思路吗

**Comment by molon** [comment]
。。 你转成 expressionAttrStr 之前记录一下好啦。。
