### ISSUE TITLE
看看这个问题，大量的数据加载太慢了

### ISSUE THREAD

**Issue by xyt243135803** [molon/MLLabel#79]
问题描述
我在cell中使用MLLinkLabel控件，大量的数据界面完全卡死；
debug的结果是  label.attributedText = attrS;  这句赋值时间长达1秒，而且文本数据不显示；

参考数据

@"312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999312276998631694997664364649949979989899993122769986316949976643646499499799898999931227699863169499766436464994997998989999"

**Comment by molon** [comment]
@xyt243135803 我也很绝望啊。。
我拿 UILabel 测试了一下，也是显示不出来，删除一部分长度就能显示了。
删除后的字符串我又放到了 MLLabel 里试了一下可以显示，但是很卡。
最后发现是正则匹配哪儿卡的，去掉就不卡了，我也很绝望啊，iOS SDK提供的就这破玩意，暂时没啥好的解决方法。。。
![image](https://user-images.githubusercontent.com/3739161/29239453-a927cc6e-7f81-11e7-9b1c-48f40adc5010.png)

**Comment by molon** [comment]
思考了一下，毕竟iOS SDK给到的正则匹配API就这性能，我会尝试提供一个口子能让外界异步去执行提取匹配link的行为，然后赋值给 LinkLabel，至少不会阻塞主线程。

**Comment by molon** [comment]
@xyt243135803 https://github.com/molon/MLLabel/commit/aadbd88de3b51b044dfcc79c9081420e3acd3afb 哥们我加了一对API，你瞅瞅，在LinkViewController的10那里有例子。

暂时只能如此了，有更好的建议及时提出来哦。

**Comment by xyt243135803** [comment]
@molon  😆，我使用模拟器测试，label高度设置超过6000行，完全渲染不出来，真机倒是可以。不过内存咔咔的涨。

我找了两个帖子解释这种情况的

https://stackoverflow.com/questions/43059823/uilabel-cannot-render-too-many-words

https://stackoverflow.com/questions/15764402/text-not-displaying-on-uilabel-when-the-text-is-too-large
